### ISSUE TITLE
上拉加载之后报这个错误是怎么回事呢？

### ISSUE THREAD

**Issue by andansky** [Solartisan/TurboRecyclerViewHelper#5]
楼主麻烦抽空看下上拉加载之后报这个错误是怎么回事呢？
java.lang.NullPointerException: Attempt to read from field 'int android.support.v7.widget.RecyclerView$ItemAnimator$ItemHolderInfo.left' on a null object reference
                                                                          at android.support.v7.widget.SimpleItemAnimator.animateDisappearance(SimpleItemAnimator.java:78)
                                                                          at android.support.v7.widget.RecyclerView.animateDisappearance(RecyclerView.java:3246)
                                                                          at android.support.v7.widget.RecyclerView.access$700(RecyclerView.java:147)
                                                                          at android.support.v7.widget.RecyclerView$4.processDisappeared(RecyclerView.java:422)
                                                                          at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:231)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3086)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2914)
                                                                          at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3277)

**Comment by solartcc** [comment]
请问，使用的是哪个版本？

**Comment by andansky** [comment]
最新的版本，我直接
listGoods.setItemAnimator(new RecyclerView.ItemAnimator() {
            @Override
            public boolean animateDisappearance(@NonNull RecyclerView.ViewHolder viewHolder, @NonNull ItemHolderInfo preLayoutInfo, @Nullable ItemHolderInfo postLayoutInfo) {
                return false;
            }

```
        @Override
        public boolean animateAppearance(@NonNull RecyclerView.ViewHolder viewHolder, @Nullable ItemHolderInfo preLayoutInfo, @NonNull ItemHolderInfo postLayoutInfo) {
            return false;
        }

        @Override
        public boolean animatePersistence(@NonNull RecyclerView.ViewHolder viewHolder, @NonNull ItemHolderInfo preLayoutInfo, @NonNull ItemHolderInfo postLayoutInfo) {
            return false;
        }

        @Override
        public boolean animateChange(@NonNull RecyclerView.ViewHolder oldHolder, @NonNull RecyclerView.ViewHolder newHolder, @NonNull ItemHolderInfo preLayoutInfo, @NonNull ItemHolderInfo postLayoutInfo) {
            return false;
        }

        @Override
        public void runPendingAnimations() {

        }

        @Override
        public void endAnimation(RecyclerView.ViewHolder item) {

        }

        @Override
        public void endAnimations() {

        }

        @Override
        public boolean isRunning() {
            return false;
        }
    });
```

我加上这个就不会报错了。
但是最新的这个版本的resetData()这个方法容易报错。
老是报数组越界之类的。旧版本的resetData没问题。

**Comment by andansky** [comment]
最新版的调用resetData()现在都是报这个错误。。。。旧版的不会。
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{fe4b454 position=4 id=-1, oldPos=1, pLpos:1 scrap [attachedScrap] tmpDetached no parent}
                                                                          at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4499)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4630)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4611)
                                                                          at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1988)
                                                                          at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:528)
                                                                          at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1347)
                                                                          at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
                                                                          at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:2977)
                                                                          at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2594)
                                                                          at android.view.View.measure(View.java:18026)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5705)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
                                                                          at android.view.View.measure(View.java:18026)
                                                                          at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1292)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:471)
                                                                          at android.widget.ScrollView.onMeasure(ScrollView.java:348)
                                                                          at android.view.View.measure(View.java:18026)
                                                                          at com.orangegangsters.github.swipyrefreshlayout.library.SwipyRefreshLayout.onMeasure(SwipyRefreshLayout.java:576)
                                                                          at android.view.View.measure(View.java:18026)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5705)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
                                                                          at android.view.View.measure(View.java:18026)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5705)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:471)
                                                                          at android.view.View.measure(View.java:18026)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5705)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
                                                                          at android.view.View.measure(View.java:18026)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5705)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:471)
                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2805)
                                                                          at android.view.View.measure(View.java:18026)
                                                                          at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2480)
                                                                          at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1457)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1692)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1335)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6755)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:603)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:572)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
                                                                          at android.os.Handler.handleCallback(Handler.java:815)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                          at android.os.Looper.loop(Looper.java:192)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5855)
                                                                          at java.lang.reflect.Method.invoke(Native Method)

**Comment by solartcc** [comment]
抱歉，最近工作比较忙，未能及时解决，接下来会花点时间review1.2.1的代码。

**Comment by andansky** [comment]
resetData报错我改了一下
/**
     *
     \* @param data additional data
     */
    public void addData(List<T> data) {
        if (data != null) {
            int pos = getItemCount();
            this.mData.addAll(data);
            notifyItemRangeInserted(pos, data.size() - 1);
        }
    }
notifyItemRangeInserted(pos, data.size() - 1);把这句换回notifyDataSetChanged();就不会报了。麻烦楼主抽空修复一下呢。

**Comment by andansky** [comment]
楼主最近干啥去了~好久没动静了啊。我又给你找了个BUG了。这个加载更多的时候新加的第一项跟原先的最后一项的间隔不见了咋整啊？感觉是因为判断了第一项不加间距导致的，应该要再加一个判断是否是加载更多时进来的数据吧
